.gitignore, packages/eslint-config-react/index.js, packages/random-name/src/index.js
Force carriage return before return.
=> feat: updated eslint setting to force carriage return before return

packages/use-query-params/package.json, packages/use-query-params/src/__tests__/index.js, packages/use-query-params/src/index.js, yarn.lock
- Fix
- Usage of useEffect with cleanUp and debounce like to fix update loop
=> fix: query params hook

lerna.json
Instead of the default angular one :)
=> ci: specify lerna changelog preset

packages/regex/src/__tests__/index.js, packages/regex/src/index.js
Adds hexadecimal regex to regex lib so it can be used for validators
=> feat: add hexa regex

packages/use-i18n/README.md, packages/use-i18n/src/__tests__/index.js, packages/use-i18n/src/index.js
add documentation about dateFnsLocale
=> fix(use-i18n): change props dateFnsLocal to dateFnsLocale

packages/use-dataloader/src/useDataLoader.js
- Optimization of hooks rerender by using some refs
- Handle enabled change and key change better
=> feat: use dataloader handle enabled changes

packages/use-i18n/src/usei18n.tsx
load function will default on global load if none is defined :)
=> fix(usei18n): correct useTranslation type

packages/use-dataloader/src/__tests__/DataLoaderProvider.test.tsx, packages/use-dataloader/src/__tests__/dataloader.test.ts, packages/use-dataloader/src/__tests__/useDataLoader.test.tsx, packages/use-i18n/src/index.ts, packages/use-i18n/src/usei18n.tsx
Correct some eslint coming with our next eslint config major update 
Made in a separate PR to avoid major bump of these packages
=> fix: correct some forthcoming eslint errors

package.json, packages/eslint-config-react/package.json, packages/eslint-config-react/shared.js, yarn.lock
Need https://github.com/scaleway/scaleway-lib/pull/490 first
BREAKING CHANGE: some new eslint rules are now enabled by default
=> feat!: update to eslint-airbnb v19

packages/use-i18n/src/usei18n.tsx
options is an optional argument
=> fix(use-i18n): optional options type on formatDate

packages/eslint-config-react/shared.js
Related rules:
- https://github.com/airbnb/javascript/blob/274c8d570155a05b016980294d4204c5711bce86/packages/eslint-config-airbnb/rules/react.js#L486
- https://github.com/airbnb/javascript/blob/274c8d570155a05b016980294d4204c5711bce86/packages/eslint-config-airbnb/rules/react.js#L491
=> feat(eslint-config-react): enforce class fields for react class

.github/renovate.json
Add dockerfile and github actions on renovate configuration
=> chore(renovate): enable dockerfile and github actions

packages/use-dataloader/src/DataLoaderProvider.tsx, packages/use-dataloader/src/types.ts, packages/use-dataloader/src/useDataLoader.ts
Use type inheritance for needPolling function
=> chore: improve needpolling type

package.json, packages/eslint-config-react/package.json, packages/jest-helpers/package.json, packages/use-query-params/package.json, pnpm-lock.yaml
Add missing peer dependencies since pnpm v7 now set `strict-peer-dependencies` to `true`
=> chore(deps): add missing strict peer deps

packages/jest-helpers/package.json, pnpm-lock.yaml
BREAKING CHANGES: only supports react 18
=> feat(jest-helpers)!: support react 18

packages/use-dataloader/src/useDataLoader.ts
- Handle useEffect needPolling is not memoized -> Dont reset timeout
- When remount the same key refetch data automatically
=> feat: improve polling timeout effect and enabled refetching

packages/use-dataloader/src/useDataLoader.ts
isLoading need to be true on mount same key but need reload
=> fix: optimistic isloading value on hook mount

package.json, packages/use-dataloader/package.json, packages/use-gtm/package.json, packages/use-i18n/package.json, packages/use-media/package.json, packages/use-query-params/package.json, packages/use-segment/package.json, pnpm-lock.yaml
- Migration
Upgrade react peer version to 18.x only
=> feat: react 18 only

packages/use-i18n/package.json, pnpm-lock.yaml
Update `international-types` to include https://github.com/QuiiBz/next-international/pull/34
=> chore(deps): update international-types to 0.3.5

packages/regex/src/index.ts
Add cidr regex, from [cidr-regex](https://github.com/silverwind/cidr-regex/blob/master/index.js)
=> feat(regex): add cidr regex

packages/use-i18n/package.json, packages/use-i18n/src/usei18n.tsx, pnpm-lock.yaml
Add back custom translate function for namespaceTranslation. Regression of #1044
=> fix(use-i18n): add back custom translate function for namespaceTranslation

packages/use-i18n/src/__tests__/usei18n.tsx, packages/use-i18n/src/__typetests__/namespaceTranslation.test.ts, packages/use-i18n/src/__typetests__/t.test.tsx, packages/use-i18n/src/usei18n.tsx
Reverts scaleway/scaleway-lib#1055
=> Revert "feat(use-i18n): required generic"

packages/regex/src/__tests__/index.ts, packages/regex/src/index.ts
=> fix: cron regex

packages/eslint-config-react/shared.js
BREAKING CHANGES: set curly to all
=> feat!: add curly rule

packages/regex/src/__tests__/index.ts, packages/regex/src/index.ts
=> feat(regex): add s3 bucket name regex

.eslintrc, package.json, packages/tsconfig/README.md, packages/tsconfig/package.json, packages/tsconfig/tsconfig.json, pnpm-lock.yaml, tsconfig.json
Needs https://github.com/scaleway/scaleway-lib/pull/1120 first
=> feat: introduce @scaleway/tsconfig

packages/use-i18n/src/__tests__/formatUnit.ts, packages/use-i18n/src/formatUnit.ts
Type was not accepting `megabit-per-second` while the code supports it
=> fix(use-i18n): correct formatUnit type

packages/regex/src/__tests__/index.ts, packages/regex/src/index.ts
=> feat: add reverse dns and dashed ip

lerna.json
Add lerna config to have emoji in changelog.
=> fix(lerna): add emoji to changelog

packages/use-i18n/package.json, pnpm-lock.yaml
See https://github.com/QuiiBz/next-international/pull/45
=> chore(deps): bump international-types to 0.3.7

packages/use-i18n/package.json, pnpm-lock.yaml
To update with https://github.com/QuiiBz/next-international/pull/46
=> chore(deps): bump international-types to 0.3.8

.github/workflows/changesets-renovate.yml
Fix https://github.com/scaleway/scaleway-lib/actions/runs/4375431641/jobs/7656136396
=> fix: changesets renovate install pnpm

.github/workflows/release.yml, .npmrc, package.json
Add a new `release` script that builds and then calls `changeset publish`
=> ci: fix changesets publish

.changeset/regex-20230322.md, packages/regex/src/index.ts
This adds Scaleway regex for access key
=> feat(regex): add Scaleway access key regex

.changeset/khaki-turtles-move.md, packages/use-i18n/src/__tests__/usei18n.tsx, packages/use-i18n/src/usei18n.tsx
enableDebugKey should display key instead of missing key
=> fix: enableDebugKey display key

.changeset/serious-singers-shout.md, packages/regex/src/__tests__/index.ts, packages/regex/src/index.ts
Add a new alphanumdashunderscore regex.
=> feat(regex): add alphanumdashunderscore regex

.changeset/honest-vans-chew.md, packages/changesets-renovate/src/__tests__/generate-changeset.ts, packages/changesets-renovate/src/index.ts
Ignore packages that are ignored in the changesets config
=> feat(changesets-renovate): ignore packages ignored in config

.github/workflows/ci.yml, .github/workflows/pull_request_title.yml, .github/workflows/release.yml
Use node lts for our CI.
PS: waiting for upgrading node version inside package.json
=> feat(node): update node version ci

.changeset/thin-oranges-return.md, packages/regex/src/__tests__/index.ts, packages/regex/src/index.ts
update the regex to allow 1 char on pathSegment.
=> fix(regex): update the path segment regex

.changeset/large-boats-exist.md, packages/cookie-consent/src/CookieConsentProvider/CookieConsentProvider.tsx, packages/cookie-consent/src/CookieConsentProvider/__tests__/index.tsx, packages/cookie-consent/src/CookieConsentProvider/__tests__/useSegmentIntegrations/emptyConfig.tsx, packages/cookie-consent/src/CookieConsentProvider/__tests__/useSegmentIntegrations/fetchError.tsx, packages/cookie-consent/src/CookieConsentProvider/__tests__/useSegmentIntegrations/networkError.tsx, packages/cookie-consent/src/CookieConsentProvider/__tests__/useSegmentIntegrations/working.tsx, packages/cookie-consent/src/CookieConsentProvider/useSegmentIntegrations.ts
Replace transitive state to loading status.
=> refactor(useCookieConsent): change isSegmentIntegrationsLoaded output

.changeset/shiny-waves-remain.md, .eslintrc, packages/eslint-config-react/shared.js
Add react/jsx-key rule to eslint config.
=> feat(eslint-config-react): add jsx-key rule

.changeset/wet-horses-prove.md, packages/cookie-consent/README.md, packages/cookie-consent/package.json, packages/cookie-consent/src/CookieConsentProvider/CookieConsentProvider.tsx, packages/cookie-consent/src/CookieConsentProvider/SegmentConsentMiddleware.tsx, packages/cookie-consent/src/CookieConsentProvider/__tests__/useSegmentIntegrations/emptyConfig.tsx, packages/cookie-consent/src/CookieConsentProvider/__tests__/useSegmentIntegrations/fetchError.tsx, packages/cookie-consent/src/CookieConsentProvider/__tests__/useSegmentIntegrations/networkError.tsx, packages/cookie-consent/src/CookieConsentProvider/__tests__/useSegmentIntegrations/working.tsx, packages/cookie-consent/src/CookieConsentProvider/helpers.ts, packages/cookie-consent/src/CookieConsentProvider/index.tsx, packages/cookie-consent/src/CookieConsentProvider/types.ts, packages/cookie-consent/src/index.ts, pnpm-lock.yaml
Add a consentMiddleware to handle new way of forward consent to destination.
https://segment.com/docs/privacy/consent-management/configure-consent-management/
=> feat(cookies): add consent middleware

.changeset/lovely-bags-kneel.md, packages/regex/src/__tests__/index.test.ts, packages/regex/src/index.ts
Add new regex for uppercase underscore
=> feat: add underscore uppercase regex

.changeset/gold-poems-begin.md, packages/regex/src/__tests__/index.test.ts, packages/regex/src/index.ts
=> feat(regex): update regex for backupkey
