- packages/regex/src/__tests__/index.js
- packages/regex/src/index.js
> feat: add mac address regex

- README.md
- babel.config.json
- package.json
- packages/use-query-params/.npmignore
- packages/use-query-params/README.md
- packages/use-query-params/package.json
- packages/use-query-params/src/__tests__/index.js
- packages/use-query-params/src/index.js
- yarn.lock
Migration of tiny hooks useQueryParams
What i did : 
- add unit test 
- avoid useless re-render
> feat(hooks): add use-query-params

- packages/use-query-params/src/__tests__/index.js
- packages/use-query-params/src/index.js
When initial search is empty we have an infinite loop
As search is empty and our state is also empty but we compare 
```js
search !== `?${stringifiedParams}`
```
We call replace every 500ms for nothing
> fix(use-query-params): correct infinite loop when search is empty

- README.md
- packages/use-query-params/README.md
- packages/use-query-params/src/__tests__/index.js
- packages/use-query-params/src/index.js
Why did not just use Router Context ?
- It cant be tested properly 😅 
By adding a context on top of this hook we make possible to useQueryParams everywhere
> feat!: base hook on search not own state

- packages/use-i18n/README.md
- packages/use-i18n/package.json
- packages/use-i18n/src/__tests__/index.js
- packages/use-i18n/src/index.js
- yarn.lock
This was causing a SIGSEGV for some reason on our tests
BREAKING CHANGE: We now expose loadDateLocale props in the Provider instead of bundling it
> fix(use-i18n)!: move date-fns dynamic import outside of library scope

- packages/use-dataloader/src/__tests__/useDataLoader.test.js
- packages/use-dataloader/src/useDataLoader.js
A tiny bug I found when trying to use the hook
> fix(use-dataloader): avoid exception when options are not defined

- packages/use-dataloader/README.md
- packages/use-dataloader/src/__tests__/useDataLoader.test.js
- packages/use-dataloader/src/reducer.js
- packages/use-dataloader/src/useDataLoader.js
Change the way that we handle data, based now on the cache directly.
It implies that : 
- DataProvider is our source of trust
- User will never cant use this hook without key
- The hook is not responsible of the data
> fix: let DataLoaderProvider handle data return from useDataLoader

- packages/use-i18n/README.md
- packages/use-i18n/package.json
- packages/use-i18n/src/__tests__/index.js
- packages/use-i18n/src/index.js
- yarn.lock
Add a new state namespaces on Provider, this state re-present namespace that are already loaded.
Add isLoaded on useTranslation hook, this params will help to avoid multi-rerender when it's not needed.
Add ReactDom unstable_batchedUpdates  to minimize number of renders
> feat(i18n): add loaded namespaces and isLoaded into useTranslation 

- packages/use-dataloader/src/DataLoaderProvider.js
- packages/use-dataloader/src/__tests__/DataLoaderProvider.test.js
- packages/use-dataloader/src/__tests__/useDataLoader.test.js
- packages/use-dataloader/src/useDataLoader.js
I forgot that to retrigger a reload the hook need to have a different key, thus we can't abstract it in the Provider
> fix(use-dataloader): move cacheKeyPrefix logic into hook to trigger reload

- packages/random-name/README.md
- packages/random-name/package.json
- packages/random-name/src/__tests__/__snapshots__/index.ts.snap
- packages/random-name/src/__tests__/index.ts
- packages/random-name/src/index.ts
- types/docker-names.d.ts
- yarn.lock
To be up to date 
This will also allow us to remove the useRandomName hook in the console codebase
> feat(random-name): base the generator on moby and expose react hook

- packages/use-dataloader/README.md
- packages/use-dataloader/src/DataLoaderProvider.tsx
- packages/use-dataloader/src/__tests__/useDataLoader.tsx
- packages/use-dataloader/src/useDataLoader.ts
This will allow us to have a global handler for errors
If a `onError` handler is specified in a `useDataloader` it will override the one from the Provider
```js
import { DataLoaderProvider, useDataLoader } from '@scaleway-lib/use-dataloader'
import React from 'react'
import ReactDOM from 'react-dom'
const failingPromise = async () => {
throw new Error('error')
}
const App = () => {
useDataLoader('local-error',  failingPromise,  {
onError: (error) => {
console.log(`local onError: ${error}`)
}
})
useDataLoader('error', failingPromise)
return null
}
const globalOnError = (error) => {
console.log(`global onError: ${error}`)
}
ReactDOM.render(
<React.StrictMode>
<DataLoaderProvider onError={globalOnError}>
<App />
</DataLoaderProvider>
</React.StrictMode>,
document.getElementById('root'),
) …
```
> feat(use-dataloader): add global onError handler

- packages/use-i18n/package.json
- packages/use-i18n/src/__tests__/formatUnit.ts
- packages/use-i18n/src/formatUnit.ts
- packages/use-i18n/src/formatters.ts
- packages/use-i18n/src/usei18n.tsx
- yarn.lock
Also with some types improvement 
Coverage difference is caused by an unused method on our cache, which we need to have to match the TS type
There is a PR open here to correct this https://github.com/formatjs/formatjs/pull/3102
> refactor(use-i18n): use @formatjs/fast-memoize instead of deprecated intl-format-cache

- packages/eslint-config-react/shared.js
Also documented the rules override we have
BREAKING CHANGE: react/no-unstable-nested-components is enforced
> feat(eslint-config-react): enable for..of syntax and react/no-unstable-nested-components

- packages/use-i18n/examples/cra/yarn.lock
- packages/use-i18n/package.json
- packages/use-i18n/src/usei18n.tsx
- yarn.lock
Original discussion https://github.com/scaleway/scaleway-lib/pull/348
Not putting this as breaking as we never supported browsers which do no support Intl.PluralRules
> chore: drop intl-pluralrules polyfill

- packages/use-dataloader/src/__tests__/useDataLoader.tsx
- packages/use-dataloader/src/useDataLoader.ts
Possibility to cancel a Promise with an enhanced promise type
> feat: request cancellation

- packages/use-dataloader/README.md
- packages/use-dataloader/src/DataLoaderProvider.tsx
- packages/use-dataloader/src/__tests__/dataloader.test.ts
- packages/use-dataloader/src/dataloader.ts
- packages/use-dataloader/src/types.ts
- packages/use-dataloader/src/useDataLoader.ts
Consider data as outdated when maxLifetime is reached. Allow stalled data detection when there are multiple useDataLoader with same key. (Performance)
> feat: refresh data on max lifetime reached

- packages/use-dataloader/src/DataLoaderProvider.tsx
- packages/use-dataloader/src/__tests__/dataloader.test.ts
- packages/use-dataloader/src/__tests__/useDataLoader.test.tsx
- packages/use-dataloader/src/dataloader.ts
- packages/use-dataloader/src/types.ts
- packages/use-dataloader/src/useDataLoader.ts
Allow users to pass a callback function that return a boolean to tell if we enable or not the polling (Allow us to drop local useState to manage this)
> feat: add needPolling callback

- package.json
- packages/use-dataloader/src/__tests__/useDataLoader.test.tsx
- packages/use-i18n/src/__tests__/usei18n.tsx
- packages/use-i18n/src/usei18n.tsx
- yarn.lock
Same as usual, to prepare for #534
> style: correct some eslint errors before new config rules

- packages/use-i18n/src/__tests__/usei18n.tsx
- packages/use-i18n/src/index.ts
- packages/use-i18n/src/usei18n.tsx
This is mainly intended when use-i18n is used server side, be it on unit tests or ssr.
On first render the provider will load date-fns locale and then rerender, trigger multiple errors on jest because we don't `act` on render.
When specified a default date-fns locale and no load function provider will not rerender
> feat(use-i18n): allow default date-fns locale instead of lazy loading

- packages/regex/src/__tests__/index.ts
- packages/regex/src/index.ts
Add alphaLower & basicDomain regex to `@scaleway/regex` package + tests
> feat: add alphaLower and basicDomain regex

- packages/use-dataloader/README.md
- packages/use-dataloader/src/types.ts
- packages/use-dataloader/src/useDataLoader.ts
Drop isFirstLoad which check if request is enabled and idle to handle the case when you mount the hook and despite of enabled but request still idle. This will be dropped when we will batch updates.
Put this condition in isLoading
> refactor: drop isFirstLoad to use isLoading only

- packages/use-i18n/README.md
Add documentation about the `formatList` function from `usei18n` hook.
> docs(use-i18n): add `formatList` to README.md

- packages/use-segment/package.json
- packages/use-segment/src/__tests__/index.tsx
- packages/use-segment/src/useSegment.tsx
- pnpm-lock.yaml
BREAKING CHANGE: use `settings.cdn` instead of `cdn`
> feat!: favor settings instead of explicit dns props

- README.md
- packages/use-gtm/.eslintrc.cjs
- packages/use-gtm/.npmignore
- packages/use-gtm/README.md
- packages/use-gtm/package.json
- packages/use-gtm/src/__tests__/__snapshots__/index.tsx.snap
- packages/use-gtm/src/__tests__/index.tsx
- packages/use-gtm/src/index.ts
- packages/use-gtm/src/scripts.ts
- packages/use-gtm/src/types.ts
- packages/use-gtm/src/useGTM.tsx
A new package with a GTM Provider/hook
This allows us to have the same DX as use-segment and consume gtm in a react way
> feat: add useGTM hook

- packages/use-gtm/src/__tests__/__snapshots__/index.tsx.snap
- packages/use-gtm/src/__tests__/index.tsx
- packages/use-gtm/src/scripts.ts
If we provided an empty or partial environment we would get `&&cookies_win=x` in the requested url
> fix(use-gtm): ensure environment auth is present before injecting url

- packages/use-gtm/src/__tests__/__snapshots__/index.tsx.snap
- packages/use-gtm/src/__tests__/index.tsx
- packages/use-gtm/src/useGTM.tsx
- packages/use-segment/src/__tests__/index.tsx
- packages/use-segment/src/useSegment.tsx
This will allow to wait for consent before loading external
> feat: do not load snippets if no settings provided

- packages/use-dataloader/src/__tests__/useDataLoader.test.tsx
- packages/use-dataloader/src/useDataLoader.ts
Use interval instead of timeouts
> feat: use interval instead of timeout

- packages/use-query-params/src/index.ts
Improve `useQueryParams` hook typing by specifying a type as an argument.
Example:
```ts
type MyRouteQueryParams = {
sort?: string
filter?: string[]
}
const { setQueryParams, replaceQueryParams} = useQueryParams<MyRouteQueryParams>()
setQueryParams( { anotherParam: "test" } )
// 👆 Argument of type '{ anotherParam: string; }' is not assignable to parameter of type 'Partial<RouteQueryParams>'
replaceQueryParams({ test: 'test' })
// 👆 Argument of type '{ test: string; }' is not assignable to parameter of type 'RouteQueryParams'.
```
> feat(useQueryParams): add generic typing

- packages/regex/src/__tests__/index.ts
Add tests for cidr regex, missing from #982
> test(regex): add cidr tests

- packages/use-i18n/src/__tests__/usei18n.tsx
- packages/use-i18n/src/__typetests__/t.test.tsx
- packages/use-i18n/src/types.ts
- tsconfig.json
Support React Components in params value for `@scaleway/use-i18n`
> feat(i18n): add types for React Components in params value

- packages/use-i18n/src/__tests__/usei18n.tsx
- packages/use-i18n/src/types.ts
- packages/use-i18n/src/usei18n.tsx
`useI18n()` / `namespaceTranslation()` now always require a generic to be passed to force type-safety.
> feat(i18n): always required Locale generic

- packages/use-i18n/src/__tests__/usei18n.tsx
- packages/use-i18n/src/__typetests__/namespaceTranslation.test.ts
- packages/use-i18n/src/__typetests__/t.test.tsx
- packages/use-i18n/src/usei18n.tsx
When using `useI18n()` / `useTranslation()` without providing a generic for the locale, `t` and `namespaceTranslation` will throw an error (`You must pass a generic argument to ****`) to enforce the usage of a Locale.
> feat(use-i18n): required generic

- packages/use-i18n/src/__tests__/usei18n.tsx
- packages/use-i18n/src/__typetests__/namespaceTranslation.test.ts
- packages/use-i18n/src/__typetests__/t.test.tsx
- packages/use-i18n/src/usei18n.tsx
Reverts scaleway/scaleway-lib#1059
> Revert "feat(use-i18n): required generic"

- packages/use-i18n/src/__tests__/usei18n.tsx
- packages/use-i18n/src/__typetests__/namespaceTranslation.test.ts
- packages/use-i18n/src/__typetests__/t.test.tsx
- packages/use-i18n/src/usei18n.tsx
BREAKING CHANGE: Required generic for useI18n() / useTranslation.
When using useI18n() / useTranslation() without providing a generic for the locale, t and namespaceTranslation will throw an error (You must pass a generic argument to ****) to enforce the usage of a Locale.
> feat(use-i18n)!: required generic

- packages/regex/src/__tests__/index.ts
- packages/regex/src/index.ts
For iam resources names, I need to be able to validate this regex.
> feat(regex): add alphanumdashunderscoredotsparenthesis regex

- .github/renovate.json
Fix https://github.com/scaleway/scaleway-lib/issues/563
> fix(renovate): remove matchManagers & matchPackageNames

- README.md
- packages/jest-helpers/package.json
- packages/outdated-browser/package.json
- packages/random-name/package.json
- packages/regex/package.json
- packages/use-dataloader/package.json
- packages/use-gtm/package.json
- packages/use-i18n/package.json
- packages/use-media/package.json
- packages/use-query-params/package.json
- packages/use-random-name/package.json
- packages/use-segment/package.json
- packages/use-storage/package.json
- packages/validate-icu-locales/package.json
- rollup.config.mjs
BREAKING CHANGE: packages are ESM only
> feat!: publish packages as ESM only

- packages/regex/src/__tests__/index.ts
- packages/regex/src/index.ts
Regex for domain with non ASCII characters but valid for internationalized domain names (IDN).
> feat(regex): advanced domain regex for non ASCII characters

- packages/eslint-config-react/shared.js
Typescript extensions is missing in no-extraneous-dependencies rule.
> feat(eslint-config): exclude ts in no-extraneous-dependencies rule

- .github/workflows/changesets-renovate.yml
Checkout the current branch when running changesets-renovate on renovate PRs.
> fix: changesets renovate checkout current branch

- .changeset/nine-seals-push.md
- packages/changesets-renovate/src/index.ts
Remove `--show-current` flag from `git branch` since simple-git already returns the current branch.
> fix(changesets-renovate): current branch check

- .changeset/happy-items-look.md
- packages/changesets-renovate/src/__tests__/generate-changeset.ts
- packages/changesets-renovate/src/index.ts
Ignore workspace's root `package.json` changes, because it doesn't impact any package.
> feat(changesets-renovate): ignore changes in workspace root `package.json`

- .changeset/funny-files-roll.md
- packages/changesets-renovate/src/__tests__/generate-changeset.ts
- packages/changesets-renovate/src/index.ts
Amending a force-pushing causes an infinite loop with renovate: force-pushing causes renovate to run again and force-push, causing the GitHub action to re-run and force-pushing...
> feat(changesets-renovate): create a new commit instead of amend + fore push

- .changeset/young-shirts-unite.md
- packages/use-i18n/src/__tests__/__snapshots__/formatUnit.ts.snap
- packages/use-i18n/src/__tests__/formatUnit.ts
- packages/use-i18n/src/formatUnit.ts
Allow to specify a base (other than 10) on formatUnit function.
This way 4294967296 can format to 4 GB for example.
> fix(formatUnit): allow to change base on formatUnit

- packages/changesets-renovate/src/__tests__/generate-changeset.ts
Very small PR to remove `ts-expect-error` & `eslint-disable` in tests and replace with a cast.
> feat(changesets-renovate): remove `ts-expect-error` & `eslint-disable` in tests

- .github/workflows/ci.yml
With @philibea we discusses that the repository ci workflow was not _fork ready_.
It could be really nice to let to the maintainer the possibility to trigger workflows on open source, external contributions.
In order to let it work, we need to listen to the pull request event as open source contribution are not `push` on original repository.
> ci(ci job): handle github action workflows for forks

- .changeset/pr-growthbook.md
The changeset I wrote in my PR refer to incorrect name of package before review was applied.
This make the release job fail on main branch. See here https://github.com/scaleway/scaleway-lib/actions/runs/5782763966
- change name of changeset file starting with pr
- change the name of the declared package to match existing one
> docs(changeset): fixup changeset for growthbook package init

- .changeset/chilly-tigers-bathe.md
- packages/use-i18n/src/types.ts
Not sure why there is an OOM when running eslint but not when running tsc.
```ts
// Before
export type ScopedValue<Locale extends BaseLocale, Scope extends Scopes<Locale> | undefined, Key extends LocaleKeys<Locale, Scope>> = Scope extends undefined ? IsPlural<Key, Locale> extends true ? Locale[`${Key}#${PluralSuffix}`] : Locale[Key] : IsPlural<Key, Locale> extends true ? Locale[`${Scope}.${Key}#${PluralSuffix}`] : Locale[`${Scope}.${Key}`];
// After
export type ScopedValue<Locale extends BaseLocale, Scope extends Scopes<Locale> | undefined, Key extends LocaleKeys<Locale, Scope>> = Scope extends undefined ? Locale[Key] : Locale[`${Scope}.${Key}`];
```
> fix(use-i18n): oom when running eslint

- .changeset/light-dots-tell.md
- packages/regex/src/__tests__/index.ts
- packages/regex/src/index.ts
Add `pathSegment` and `absolutePath` regex
> feat(regex): add `pathSegment` and `absolutePath` regex

- .changeset/few-peas-dream.md
- packages/use-growthbook/src/AbTestProvider.tsx
- packages/use-growthbook/src/index.ts
I face missing exported types from the provider in order to easily declare them.
We could counter by getting them from AbTestProvider.
- export two types from callback
> feat(use-growthbook): export type on provider init

- .changeset/silver-camels-worry.md
- packages/cookie-consent/src/CookieConsentProvider/CookieConsentProvider.tsx
- packages/cookie-consent/src/CookieConsentProvider/__tests__/index.tsx
- packages/cookie-consent/src/CookieConsentProvider/index.tsx
We were having an issue on localhost when trying to remove a cookie. It wasn't always working, apparently we need to pass the path (cookie options in our case) to make it work. You can have more info by clicking on the lint below
https://stackoverflow.com/a/28119715
> feat(cookie-consent): pass cookie options when deleting one consent

- .changeset/brave-needles-play.md
- packages/cookie-consent/src/CookieConsentProvider/__tests__/useSegmentIntegrations/working.tsx
- packages/cookie-consent/src/CookieConsentProvider/useSegmentIntegrations.ts
We have some missing events in Amplitude but we receive them in Segment.
It does seems to be due to the mapping of consent categories with Amplitude.
- [revert modification that introduce an inverted condition here](https://github.com/scaleway/scaleway-lib/pull/1494#discussion_r1332942387) 
- fixup snapshots
> fix(cookies): bind name for segment integration instead of creationName

- .changeset/rotten-beans-juggle.md
- README.md
Some links are broken in the global readme of the repository
- bundlephobia pages are not working because package does not export entrypoints
- they are broken links in growthbook package
- fix global readme links
- re-add main entry to make bundlephobia working
@QuiiBz What is your opinion on re-adding main key on package ?
> docs(readme): fixup links and bundlephobias

- .changeset/healthy-ghosts-compare.md
- README.md
- packages/cookie-consent/README.md
Found out they were still some small issues in scaleway lib documentation files
- remove duplicated title in global readme file
- rename heading1 of cookie-consent package to remove reference of shire
> docs(readme): fixup typos in Readme files

- .changeset/khaki-impalas-train.md
- packages/cookie-consent/src/CookieConsentProvider/CookieConsentProvider.tsx
- packages/cookie-consent/src/CookieConsentProvider/__tests__/index.tsx
- packages/cookie-consent/src/CookieConsentProvider/__tests__/useSegmentIntegrations/emptyConfig.tsx
- packages/cookie-consent/src/CookieConsentProvider/__tests__/useSegmentIntegrations/fetchError.tsx
- packages/cookie-consent/src/CookieConsentProvider/__tests__/useSegmentIntegrations/networkError.tsx
- packages/cookie-consent/src/CookieConsentProvider/__tests__/useSegmentIntegrations/working.tsx
- packages/cookie-consent/src/CookieConsentProvider/useSegmentIntegrations.ts
Add isSegmentLoading to be able to know when segment has not finished fetching integrations.
> feat(useCookieConsent): add isSegmentLoading state

- .changeset/plenty-dogs-shake.md
- packages/use-segment/src/__tests__/SegmentProvider.test.tsx
- packages/use-segment/src/__tests__/index.tsx
- packages/use-segment/src/useSegment.tsx
Add ready state to prevent calling events from Provider when analytics instance is not ready
> fix(useSegment): add ready state

- .changeset/nice-seahorses-protect.md
- packages/use-i18n/src/__tests__/usei18n.tsx
- packages/use-i18n/src/usei18n.tsx
Add the possibility to avoid useless re-render at first render of the provider,  i add  a`loadDateLocale` props which is non async and will act as a default value of dateFns based on the current value of the user.
```javascript
loadDateLocaleAsync = async (locale: string) => {
if (locale === 'en') {
return (await import('date-fns/locale/en-GB')).enGB
}
if (locale === 'fr') {
return (await import('date-fns/locale/fr')).fr
}
if (locale === 'es') {
return (await import('date-fns/locale/es')).es
}
return (await import(`date-fns/locale/en-GB`)).enGB
},
```
```javascript
import { enGB, fr as frDateFns } from 'date-fns/locale'
loadDateLocale = (locale: string) => {
if (locale === 'en') {
return enGB
}
if (locale === 'fr') {
return frDateFns
}
return enGB
},
```
> fix(use-i18n): add non async loadDateLocalFns 

- .changeset/chatty-lemons-return.md
- packages/random-name/src/index.ts
When generating a random name for a resource, we have a different standard between the go SDK and scaleway-lib. Specifically, scaleway-lib is missing Xavier Niel as a possible generated name.
This MR fixes it :nerd_face: 
Reference: https://github.com/scaleway/scaleway-sdk-go/blob/master/namegenerator/name_generator.go#L632
> fix(random-name): add xavier niel for consistency with scaleway-sdk-go

- .github/workflows/ci.yml
- jest.config.tsd.mjs
- package.json
- packages/use-i18n/src/__typetests__/namespaceTranslation.test.ts
- packages/use-i18n/src/__typetests__/t.test.tsx
- packages/use-i18n/src/__typetests__/tsconfig.json
- pnpm-lock.yaml
- tstyche.config.json
Migration from "tsd-lite" to "tstyche".
waiting https://github.com/tstyche/tstyche/issues/17
close https://github.com/scaleway/scaleway-lib/pull/1658
> refactor(type-test): use new runner for types tests

- .changeset/wet-grapes-eat.md
- packages/eslint-config-react/typescript.js
Remove deprecation rule from eslint as the rule is already handled by typescript.
> feat(eslint-config): remove deprecation rule

- .changeset/olive-cars-double.md
- packages/cookie-consent/src/CookieConsentProvider/SegmentConsentMiddleware.tsx
Use the right type of date inside consent object
https://segment.com/docs/privacy/consent-management/consent-in-segment-connections/#consent-object
> fix(segment): use right object for consent

- .changeset/new-games-act.md
- packages/cookie-consent/package.json
- packages/random-name/package.json
- packages/regex/package.json
- packages/use-dataloader/package.json
- packages/use-growthbook/package.json
- packages/use-segment/package.json
- packages/use-storage/package.json
- packages/validate-icu-locales/package.json
Some of our apps are not yet compatible with `esm` natively and can't use the `module` exported files on server.
In order to to recompile them locally and as they are exported directly, let's add the legacy `main` attribute for retrocompatibility.
Recent package will use `exports` syntax and ignore the main one
- add main on package that have CommonJS exported assets
> feat: add legacy main attribut for legacy node applications

- .changeset/popular-fans-act.md
- packages/use-i18n/src/usei18n.tsx
currently if files are not named with basic language 2 letters length (such as 'en', 'fr', ...) then default locales are not found.
If we have files matching the languages pattern of browser, such as (fr-FR, en-US, etc) then it was not taken into account.
This PR fix this
> fix(i18n): add default locales from browser to be able to select them

- .changeset/fresh-zebras-eat.md
- packages/changesets-renovate/README.md
- packages/changesets-renovate/src/__tests__/__snapshots__/generate-changeset.test.ts.snap
- packages/changesets-renovate/src/__tests__/generate-changeset.test.ts
- packages/changesets-renovate/src/index.ts
Hello,
I've added an option to disable the verification that it's running in a renovate branch `SKIP_BRANCH_CHECK`. This helps with projects that may have a custom branch name for renovate (#1706) or if you are using GitLab CI where you are in a detached HEAD state.
> feat(changesets-renovate): add option to skip branch check

- .changeset/ninety-pianos-tan.md
- packages/use-dataloader/src/DataLoaderProvider.tsx
- packages/use-dataloader/src/__tests__/useInfiniteDataLoader.test.tsx
- packages/use-dataloader/src/index.ts
- packages/use-dataloader/src/types.ts
- packages/use-dataloader/src/useInfiniteDataLoader.ts
Implement useInfiniteDataLoader to handle Load More on our UI
> feat: add useInfiniteDataLoader
